// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnxsa1a-xTKEKPoIqCsMWxFTcNAR5cp90',
    appId: '1:848327280637:web:1c1f8a3959dbb3bb6b3b94',
    messagingSenderId: '848327280637',
    projectId: 'budget-manager-18a24',
    authDomain: 'budget-manager-18a24.firebaseapp.com',
    databaseURL: 'https://budget-manager-18a24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budget-manager-18a24.appspot.com',
    measurementId: 'G-71CT4CLYKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoSSoMiFwlbCGtM33yT_TlegRG28z4oM',
    appId: '1:848327280637:android:7034aa957d316d436b3b94',
    messagingSenderId: '848327280637',
    projectId: 'budget-manager-18a24',
    databaseURL: 'https://budget-manager-18a24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budget-manager-18a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQmNnZjiVwEZaey21Bxp1qTsTB68Gs4E',
    appId: '1:848327280637:ios:cc1c71cfa3605bfe6b3b94',
    messagingSenderId: '848327280637',
    projectId: 'budget-manager-18a24',
    databaseURL: 'https://budget-manager-18a24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budget-manager-18a24.appspot.com',
    iosClientId: '848327280637-lgf2d99q2mihftlrbj7tcr0novm6u5dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeQmNnZjiVwEZaey21Bxp1qTsTB68Gs4E',
    appId: '1:848327280637:ios:cc1c71cfa3605bfe6b3b94',
    messagingSenderId: '848327280637',
    projectId: 'budget-manager-18a24',
    databaseURL: 'https://budget-manager-18a24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'budget-manager-18a24.appspot.com',
    iosClientId: '848327280637-lgf2d99q2mihftlrbj7tcr0novm6u5dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManager',
  );
}
